export const OWNED_EQUIPMENT = Object.freeze([
  'smith-machine',
  'adjustable-bench',
  'cable-machine',
  'belt-squat',
  'trap-bar',
  'dumbbells',
  'pull-up-bar',
  'dip-bars',
  'exercise-bike',
  'incline-treadmill',
  'slant-board',
  'balance-pad',
  'rehab-bands',
  'weighted-wagon'
]);

export const exercises = {
  seatedCalf: {
    id: 'seated-dumbbell-calf-raise',
    name: 'Seated Dumbbell Calf Raise',
    purpose: 'Build soleus and plantar-flexor strength with controlled Achilles loading.',
    sets: 4,
    reps: '8–12',
    effort: 'Hard but controlled',
    rpe: '7–8',
    restSec: 90,
    tempo: '2 sec up • 1 sec hold • 3 sec down',
    cue: 'Sit on your adjustable bench, keep the knee bent, and reach full controlled heel height.',
    loadTier: 'moderate',
    tags: ['soleus','calf-strength'],
    equipment: ['adjustable-bench','dumbbells'],
    evidence: 'Supportive',
    videoSource: 'NHS inform',
    videoUrl: 'https://www.youtube.com/watch?v=RsdE7Ehwhvc',
    videoNote: 'Short exercise-specific demonstration'
  },
  singleCalf: {
    id: 'single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    purpose: 'Build unilateral calf strength, heel-rise height and endurance.',
    sets: 3,
    reps: '6–10',
    effort: 'Hard but clean',
    rpe: '7–8',
    restSec: 120,
    tempo: '2 sec up • 1 sec hold • 3 sec down',
    cue: 'Use your slant board or a stable step only if it allows full control; prioritize heel height over load.',
    loadTier: 'high',
    tags: ['gastroc','calf-strength'],
    equipment: ['slant-board','dumbbells'],
    evidence: 'Supportive',
    videoSource: 'Revival Performance Physical Therapy',
    videoUrl: 'https://www.youtube.com/watch?v=blPyPFXR-WU',
    videoNote: 'Exercise-specific physical therapist demonstration'
  },
  beltSquat: {
    id: 'belt-squat',
    name: 'Belt Squat',
    purpose: 'Build quad and glute strength without requiring a leg press or barbell back squat.',
    sets: 3,
    reps: '8–10',
    effort: 'Hard',
    rpe: '7–8',
    restSec: 150,
    tempo: '3 sec down • controlled up',
    cue: 'Stay tall, keep the knees tracking over the feet, and use a pain-free depth you can control.',
    loadTier: 'moderate',
    tags: ['quad','glute','strength'],
    equipment: ['belt-squat'],
    evidence: 'General strength evidence',
    videoSource: 'Flow High Performance',
    videoUrl: 'https://www.youtube.com/watch?v=lSN8HtptOvE'
  },
  rdl: {
    id: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    purpose: 'Build hamstrings and hip-extension strength for athletic movement without conventional deadlifting.',
    sets: 3,
    reps: '8–10',
    effort: 'Hard',
    rpe: '7–8',
    restSec: 150,
    tempo: '3 sec down • controlled up',
    cue: 'Push the hips back while keeping the trunk stable and the dumbbells close to your legs.',
    loadTier: 'low',
    tags: ['hamstring','glute','strength'],
    equipment: ['dumbbells'],
    evidence: 'General strength evidence',
    videoSource: 'NASM',
    videoUrl: 'https://www.youtube.com/watch?v=xgusDooVfKU'
  },
  stepUp: {
    id: 'bench-step-up',
    name: 'Bench Step-Up',
    purpose: 'Build controlled single-leg strength and force transfer.',
    sets: 3,
    reps: '8 / side',
    effort: 'Moderate-hard',
    rpe: '7',
    restSec: 90,
    tempo: 'Controlled',
    cue: 'Use a conservative bench height and drive through the working leg without pushing hard from the trailing foot.',
    loadTier: 'moderate',
    tags: ['single-leg','quad','glute'],
    equipment: ['adjustable-bench','dumbbells'],
    evidence: 'Supportive',
    videoSource: 'NASM',
    videoUrl: 'https://www.youtube.com/watch?v=k0_42mij5Fc'
  },
  pallof: {
    id: 'cable-pallof-press',
    name: 'Cable Pallof Press',
    purpose: 'Build trunk control for running, cutting and force transfer.',
    sets: 2,
    reps: '10 / side',
    effort: 'Controlled',
    rpe: '6–7',
    restSec: 45,
    tempo: 'Controlled',
    cue: 'Keep shoulders and hips square while resisting rotation.',
    loadTier: 'minimal',
    tags: ['trunk'],
    equipment: ['cable-machine'],
    evidence: 'General strength evidence',
    videoSource: 'NASM',
    videoUrl: 'https://www.youtube.com/watch?v=f3R99GoYvCs'
  },
  wagonBackwardDrag: {
    id: 'weighted-wagon-backward-drag',
    name: 'Weighted Wagon Backward Drag',
    purpose: 'Build low-impact leg capacity and conditioning while using your weighted wagon as a sled substitute.',
    sets: 4,
    reps: '15–25 yd',
    effort: 'Smooth and controlled',
    rpe: '5–7',
    restSec: 60,
    tempo: 'Steady backward steps',
    cue: 'Face the wagon, keep your torso tall, take short controlled backward steps, and use a load that rolls smoothly without jerking.',
    loadTier: 'moderate',
    tags: ['conditioning','quad','sled','gait-capacity'],
    equipment: ['weighted-wagon'],
    evidence: 'General strength and conditioning evidence; use as an implementation option, not an Achilles clearance test.',
    videoSource: 'Resilient Performance Physical Therapy',
    videoUrl: 'https://www.youtube.com/watch?v=YyaNNPy-FNQ'
  },
  bike: {
    id: 'easy-bike',
    name: 'Easy Bike',
    purpose: 'Maintain conditioning while reducing impact demand.',
    sets: 1,
    reps: '15–25 min',
    effort: 'Easy-moderate',
    rpe: '4–6',
    restSec: 0,
    tempo: 'Steady',
    cue: 'Keep cadence smooth and symptoms quiet.',
    loadTier: 'low',
    tags: ['conditioning'],
    equipment: ['exercise-bike'],
    evidence: 'General conditioning evidence',
    videoUrl: ''
  }
};

export function usesOnlyOwnedEquipment(exercise) {
  return (exercise.equipment || []).every(item => OWNED_EQUIPMENT.includes(item));
}
