export type Tab = "Today" | "Plan" | "Progress" | "Tests" | "More";
export type Readiness = { level: string; reason: string; action: string };
export type Answers = {
  pain: string;
  stiffness: string;
  swelling: string;
  previousResponse: string;
  recovery: string;
  unusualSymptoms: string[];
};
export type CheckIn = {
  id: string;
  date: string;
  createdAt: string;
  answers: Answers;
  readiness: Readiness;
  rulesetVersion?: string;
};
export type SetLog = {
  inheritedFields?: string[];
  feedbackConfirmed?: boolean;
  load?: string;
  reps?: string;
  complete?: boolean;
  rpe?: string;
  quality?: string;
  symptoms?: string;
};
export type WorkoutLog = Record<string, { sets: SetLog[] }>;
export type Exercise = {
  illustrationId?: string;
  requestedMovement?: string;
  selectionReason?: string;
  block?: string;
  progressionTarget?: { action: string; text: string; reason: string; sourceSessionId: string; previousLoad: number; ruleId: string; matrixVersion: string; sourceIds: string[] };
  equipment?: string[];
  skipReason?: string;
  strengthModule?: boolean;
  originalId?: string;
  id: string;
  name: string;
  sets: number;
  reps: string;
  rpe: string;
  restSec: number;
  cue: string;
  purpose: string;
  evidence: string;
  videoUrl: string;
  videoSource?: string;
  adjustment?: string;
  unit?: string;
};
export type Workout = {
  sessionFormat?: string;
  templateVersion?: string;
  blockProgression?: any[];
  blockMatrixVersion?: string;
  conditioningReplaced?: boolean;
  progressionAllowed?: boolean;
  id: string;
  title: string;
  phase: string;
  items: Exercise[];
  retained?: Exercise[];
  stopped?: boolean;
  notes?: string[];
  omitted?: { id: string; name: string; reason: string }[];
};
export type Session = {
  sessionFormat?: string;
  templateVersion?: string;
  blockProgression?: any[];
  blockMatrixVersion?: string;
  revision?: number;
  updatedAt?: string;
  correctionHistory?: any[];
  durationMs?: number;
  startedAt?: string;
  finishedAt?: string;
  workoutTimer?: any;
  coachingContext?: any;
  originalPlan?: Exercise[];
  id: string;
  date: string;
  createdAt: string;
  workoutId: string;
  workoutTitle?: string;
  exerciseLog: WorkoutLog;
  readiness?: Readiness;
  status: string;
  overallDifficulty?: string;
  immediateAchillesResponse?: string;
  notes?: string;
  plannedItems?: Exercise[];
  exerciseChanges?: { fromName: string; toName: string | null; reason: string; scope: string; at: string }[];
  rulesetVersion?: string;
  domain?: string;
  exposureLevel?: string;
  movementQuality?: string;
  minutes?: string;
  sessionRPE?: string;
  nextDayResponse?: unknown;
};
export type Values = Record<string, string | string[]>;
export type Assessment = {
  id: string;
  values: Values;
  completedAt?: string;
  updatedAt: string;
  step: number;
};
export type Profile = {
  conditioningFrom?: string;
  previousStrengthStyle?: string;
  equipmentUpdate20260915?: boolean;
  scheduleMoves?: { from: string; to: string; kind: string }[];
  exerciseChoices?: Record<string, { id: string; reason: string; effectiveFrom?: string }>;
  id: string;
  availableDays: string[];
  equipment: string[];
  strengthStyle?: string;
};
